### ISSUE TITLE
Resume method for unify command

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#144]
Due to `unify` operation is a long running task for big databases, it would be ideal to have checkpoints in case of failure. Therefore, the process would be able to restart from the point it stopped.

Unify consists on two phases. First, matches are calculated in memory. Second, each match is ensured in the database merging identities. It would be possible to store these matches in a temporary file of table, removing entries once they're applied to the database. Thus, if the process fails, it will start again reading and writing those entries instead of start over calculating the matches.

**Comment by valeriocos** [comment]
I have just pushed a PR with the purpose of kickstarting a discussion to address this enhancement. @sduenas, please have a look at it.

**Comment by sduenas** [comment]
As we discussed, we have to get an agreement before continuing working on this. The main problem is how the command should work when multiple databases are in use. In this case, a common file won't work. It will need a specific file for each database. One option would be to store matching data in a temporary table on the database.

If we think in sortinghat working as a server, I think is a better idea to store intermediate results into files. One file for each database. The only problem is where to store the files.

What do you think, @valcos?

**Comment by valeriocos** [comment]
With the current implementation, If SortingHat is executed from a docker container, there will be no problems (as confirmed with the operation team). Every intermediate file will exist in the container and if need, we can persist the files in the file system in a way that they will not clash each other (for instance using the name of the db). This solution is similar to the file logs of other GrimoireLab components (perceval, mordred, etc.).

If we consider SortingHat like a server, I'm not really in favor of polluting the database schema with tables that don't belong to the domain model, nevertheless we can take this path if needed.  I prefer to store intermediate results into files, however this implies that we need a unified format to transparently read the results from the database and files (as done in PR #146 with the method `jsonize`), otherwise we will have duplicated logic (as shown in PR #152). 
The files could be stored in a common directory (e.g., ~/.sortinghat.d/) where their names could be the database names.

Anyway, I'm open to any solution you propose. In case we don't find a solution that makes us happy, we can always postpone this enhancement and move the focus on other tasks.

**Comment by sduenas** [comment]
> If we consider SortingHat like a server, I'm not really in favor of polluting the database schema with tables that don't belong to the domain model, nevertheless we can take this path if needed. I prefer to store intermediate results into files, however this implies that we need a unified format to transparently read the results from the database and files (as done in PR #146 with the method jsonize), otherwise we will have duplicated logic (as shown in PR #152).
> The files could be stored in a common directory (e.g., ~/.sortinghat.d/) where their names could be the database names.

I think you're right. Let's proceed with this solution. One file per database. In any case, I think you should find a better name for `jsonize`. If the idea is have a similar method for reading/writting data, something like marshall_matching_data and unmarshall_matching_data will work better.

**Comment by valeriocos** [comment]
@sduenas, I have updated the PR https://github.com/chaoss/grimoirelab-sortinghat/pull/146 according to what we discussed. Please, have a look at it
