### ISSUE TITLE
[ui] Support pagination in individuals query

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sortinghat#303]
The current query only fetches the first page of individuals. This query should be able to request different pages and specify the number of items to retrieve on each query:

Here is the implementation of the pagination type in GraphQL.
https://github.com/chaoss/grimoirelab-sortinghat/blob/muggle/sortinghat/core/schema.py#L77

**Comment by dlumbrer** [comment]
After thinking about the issue, I submitted a PR (#307) that adds the functionality of the pagination to the query (test included).
I didn't touch anything related to the UI because I think that that functionality falls on #306. 

Please @sduenas , check my comment. If you agree, I will work on the other issue and adapt the components to use the pagination functionality (after mocking up the design as we talked about).

**Comment by sduenas** [comment]
Fixed by #307
